apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: wordpress-secret
  data:
    - secretKey: wordpress-password
      remoteRef:
        key: prod/wordpress
        property: password